name: Descargar Modelo IA
on: 
  workflow_dispatch: # Esto activa el botón manual

jobs:
  download:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Necesario para crear el Release
    steps:
      - name: Descargar desde Hugging Face
        run: |
          curl -L https://huggingface.co/prithivMLmods/SmolLM2-135M-F32-GGUF/resolve/main/SmolLM2-135M-Instruct.Q3_K_S.gguf
      
      - name: Crear Release y Subir Modelo
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v1.1-modelos
          files: modelo.gguf
          name: "Lanzamiento de Modelos IA"
          body: "Modelo SmolLM2-135M listo para descargar."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
